apiVersion: apps/v1
kind: Deployment
metadata:
  name: any-old-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: any-old-app
  template:
    metadata:
      labels:
        app: any-old-app
    spec:
      containers:
      - image: kevincai2022/any-old-app:3ea591cf
        name: any-old-app

---

apiVersion: v1
kind: Service
metadata:
  name: any-old-app
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: "any-old-app"
    port: 3000
  selector:
    app: any-old-app
