---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: dynatrace

---
apiVersion: v1
kind: Namespace
metadata:
  name: fleet-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: keda

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-issuers
