---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Namespace
metadata:
  name: cattle-system

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Namespace
metadata:
  name: dynatrace

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Namespace
metadata:
  name: fleet-system

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Namespace
metadata:
  name: keda

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Namespace
metadata:
  name: cluster-issuers
